extends: default

rules:
  line-length:
    max: 120
    level: warning
  truthy:
    allowed-values: ["true", "false"]
    check-keys: false
  comments:
    min-spaces-from-content: 1
  document-start:
    present: true
  braces:
    max-spaces-inside: 1
  brackets:
    max-spaces-inside: 1
